const express = require("express");
const router = express.Router();
const employee = require("../../../Controllers/employee");
router.post("/addemployee", employee.addEmployee);
router.delete("/deleteemployee", employee.deleteEmployee);
router.delete("/deletetable", employee.deletetable);
router.put("/updateemployee", employee.updateEmployee);
router.get("/getemployee", employee.getEmployee);
router.get("/getemployeeByGSI", employee.getEmployeebyGSI);
router.get("/getemployeeById", employee.getEmployeebyId);
module.exports = router;
